 users:
    image: postgres:latest
    command: postgres -c 'max_connections=1000'
    volumes:
      - /var/local/sdb/users_test:/var/lib/postgresql/data
    container_name: users_test
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=morgan
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

 redis:
    image: redis:6.0
    ports:
      - 6380:6379

